### ISSUE TITLE
GRUB2 ISO Live Entry for Salix 15.0 Xfce 64 Bits

### ISSUE THREAD

**Issue by inukaze** [gapan/www.salixos.org#2]
Hi there, i had a customized GRUB2 on a USB Pedrive. and i had wrote the follow entry :

> 		menuentry 'Salix OS 15.0 - Xfce (64 Bits)'	{
> 			load_video
> 			search --set root -u a9cec8d3-2770-4cb9-acbb-55479a5370f8
> 			search.fs_uuid a9cec8d3-2770-4cb9-acbb-55479a5370f8
> 			set isofile='ISO/salixlive64-xfce-15.0.iso'
> 			set gfxpayload=keep
> 			loopback loop (hd0,msdos3)/$isofile
> 			parametros="max_loop=255 vga=791 locale=es_ES.utf8 keymap=es useswap=yes copy2ram=no tz=America/Caracas hwc=localtime runlevel=4"
> 			linux (loop)/boot/vmlinuz $parametros fromiso=$isofile
> 			initrd (loop)/boot/initrd.gz
> 		}

Well when i try to boot it i got the follow message : 

***** Live System Error - Live media not detected - exiting * * ***

The thing is not booting to Live Session.

What i can change to boot correctly the iso in live mode from GRUB2 using just the iso file ?

**Comment by gapan** [comment]
I'm sorry, but this is the issue tracker for the main website for Salix. It is not a place for generic support for the distribution. Please post your problem on the Salix forums at https://forum.salixos.org/

**Comment by inukaze** [comment]
Theme solved on -> https://forum.salixos.org/viewtopic.php?t=8801
